export { type CreateLLMClientOptions, createLLMClient } from './prompts/create-executor'
export { type GenerationConfig, PromptExecutor } from './prompts/executor'
export {
  analysisPromptV2,
  type HookGeneratorPromptContext,
  hookGeneratorPromptV2,
} from './prompts/v2'
export {
  type AnalysisResponse,
  AnalysisResponseSchema,
  // Types
  type Archetype,
  // Schemas
  ArchetypeSchema,
  type CoreThesis,
  CoreThesisSchema,
  type CuriosityQuestionWorkflowInput,
  type CuriosityQuestionWorkflowOutput,
  type Domain,
  DomainSchema,
  type HookContext,
  HookContextSchema,
  type HookGenerationResponse,
  HookGenerationResponseSchema,
  type HookGeneratorV2Response,
  HookGeneratorV2ResponseSchema,
  type HookQuestion,
  type HookQuestionOption,
  HookQuestionOptionSchema,
  HookQuestionSchema,
  type LogicalSchema,
  LogicalSchemaSchema,
  type Metadata,
  MetadataSchema,
  type Pedagogy,
  PedagogySchema,
  type QuizCard,
  QuizCardSchema,
  type QuizOption,
  QuizOptionSchema,
  type Remediation,
  RemediationSchema,
  type SourceLocation,
  SourceLocationSchema,
  type StructuralSkeleton,
  StructuralSkeletonSchema,
} from './prompts/v2/curiosity/schemas'
